[theme]
primaryColor = "#FF8C00"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFF8DC"
textColor = "#8B4513"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

